# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test Release

on:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Get tag
      env:
        BUILD_TAG: ${{ github.ref }}
      run: echo "$BUILD_TAG"

    - name: Build Type
      env:
        IS_STAGING: ${{ endsWith(github.ref, '-staging') }}
      run: echo "$IS_STAGING"

    - name: Dump Env context
      env:
        ENV_CONTEXT: ${{ toJSON(env) }}
      run: echo "$ENV_CONTEXT"

    - name: If Staging
      if: ${{ endsWith(github.ref, '-staging') }}
      run: echo "This is staging"

    - name: If Not Staging
      if: ${{ !endsWith(github.ref, '-staging') }}
      run: echo "This is not Staging"
